# Generated by Django 4.1.3 on 2022-11-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upload', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ping', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sponsor', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=False)),
            ],
        ),
    ]
